[project]
authors = ["addis"]
entry = "main.sw"
license = "Apache-2.0"
name = "src-6-vault-connector"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
